apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-pvc
  namespace: auth
  labels:
    app: openldap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: auth
  labels:
    app.kubernetes.io/name: openldap
    app: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
      app: openldap
  replicas: 1
  template:
    metadata:
      annotations:
        volumePermissions.enabled: "true"
      labels:
        app.kubernetes.io/name: openldap
        app: openldap
    spec:
      initContainers:
        - name: volume-permissions
          image: docker.io/bitnami/bitnami-shell:10-debian-10-r265
          command:
            - /bin/bash
            - '-ec'
          args:
            - |
              mkdir -p /bitnami/openldap
              chown -R "1001:1001" "/bitnami/openldap"
          resources: {}
          volumeMounts:
            - name: data
              mountPath: /bitnami/openldap
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
      containers:
      - name: openldap
        image: bitnami/openldap:latest
        imagePullPolicy: "Always"
        env:
          - name: LDAP_ROOT
            value: "dc=techboyd,dc=com"
          - name: LDAP_ADMIN_USERNAME
            value: "admin"
          - name: LDAP_CONFIG_ADMIN_ENABLED
            value: "yes"
          - name: LDAP_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: adminpassword
                name: openldap
          - name: LDAP_USERS
            valueFrom:
              secretKeyRef:
                key: users
                name: openldap
          - name: LDAP_PASSWORDS
            valueFrom:
              secretKeyRef:
                key: passwords
                name: openldap
        ports:
          - name: tcp-ldap
            containerPort: 1389
        volumeMounts:
          - name: data
            mountPath: "/bitnami/openldap"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: openldap-pvc